apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: exercises/helm/nginx-deployment
    repoURL: https://github.com/matthewglassman/UdacityCloudNativeTraining
    targetRevision: HEAD