name: TechTrends - Package with Docker

#Determines when the action will run. Triggers the workflows on a push
#event only on the main branch
on:
  push:
    branches: [ main ]

#Workflow with one job
jobs:
  #There is one job called build that will be run on latest ubuntu
  build:
    runs-on: ubuntu-latest

    