name: TechTrends - Package with Docker

#Determines when the action will run. Triggers the workflows on a push
#event only on the main branch
on:
  push:
    branches: [ main ]

#Workflow with one job
jobs:
  #There is one job called build that will be run on latest ubuntu
  build:
    runs-on: ubuntu-latest

    #Sequences of steps to perform for the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build It and Push It to DockerHub
        uses: docker/build-push-action@v2
        with:
          context:  ./project
          file: Dockerfile
          platforms:  linux/amd64
          push: true
          tags: doughdocker/techtrends:latest